# Generated by Django 3.0 on 2022-05-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='label',
            field=models.TextField(default='N/A', max_length=10),
        ),
    ]
